const applicationset = [{
    title: "Frontend Developer",
    organization: "Twitter",
    maxApplicants: 100,
    jobtype: "remote",
    status: "accepted",
    salary: 40000,
    },
    {
        title: "Backend Developer",
        maxApplicants: 10,
        organization: "TikTok",
        jobtype: "on-site",
        status: "pending",
        skillsets: ["Redux.js", "Node.js", "AWS", "MongoDB", "Socket.io", "Express.js"],
        salary: 40000,
        },
    {
        title: "UI/ UX Designer",
        maxApplicants: 50,
        organization: "Google",
        jobtype: "remote",
        status: "waitlist",
        skillsets: ["Figma", "Webflow", "HTML", "CSS", "Adobe Studio"],
        salary: 40000,
        },
    {
        title: "Web3 Developer",
        maxApplicants: 90,
        organization: "KFC",
        jobtype: "hybrid",
        status: "accepted",
        skillsets: ["Etheruem", "Solidity", "Rust", "AWS", "Node.js", "Express.js"],
        salary: 50000,
        },
    {
        title: "Devops",
        maxApplicants: 100,
        organization: "Klarna",
        jobtype: "remote",
        status: "pending",
        skillsets: ["NoSQL", "MySL", "Express.js", "Typescript", "Javascript", "Kubernetes"],
        salary: 90000,
        },
    {
        title: "Fullstack Developer",
        maxApplicants: 10,
        organization: "Instagram",
        jobtype: "on-site",
        status: "pending",
        skillsets: ["Node.js", "Express.js", "Redis", "HTML", "AWS"],
        salary: 120000,
        },
    {
        title: "Blockchain Developer",
        maxApplicants: 150,
        organization: "Goil",
        jobtype: "hybrid",
        status: "accepted",
        skillsets: ["Ethereum", "Solidity", "React.js", "Rust", "Javascript", "UI"],
        salary: 60000,
    },
        {
        title: "PHP Developer",
        maxApplicants: 100,
        jobtype: "remote",
        organization: "Meta",
        status: "pending",
        skillsets: ["Laravel", "Python", "Node.js", "AWS", "Socket.io", "PHP"],
        salary: 220000,
    },
        {
        title: "Junior Frontend Developer",
        maxApplicants: 120,
        jobtype: "remote",
        organization: "Youtube",
        status: "rejected",
        skillsets: ["HTML", "CSS", "Javascript", "React.js", "Node.js", "Tailwind.css"],
        salary: 40000,
    },
        {
        title: "Mid-level Frontend Developer",
        maxApplicants: 100,
        organization: "RGT",
        jobtype: "remote",
        status: "accepted",
        skillsets: ["Redux", "Css", "React.js", "Typescript", "Javascript", "Bootstrap"],
        salary: 40000,
    },
    ];
    
    export default applicationset;