const jobs = [{
title: "Frontend Developer",
company: "Twitter",
maxApplicants: 100,
jobtype: "remote",
description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sapien nibh, fermentum ut molestie ac, fringilla vitae augue. Aliquam tincidunt rhoncus molestie. Vestibulum ut vestibulum felis. Proin elementum velit vitae dolor mollis, a cursus odio interdum. Aenean posuere quam id lacus facilisis, et ultricies nulla feugiat. Morbi congue tincidunt eros in mollis. Donec mollis quis tortor eget tincidunt. Nunc elementum, risus pellentesque auctor rutrum, massa leo luctus felis, et feugiat eros tellus ut tellus. Etiam lacinia condimentum velit feugiat convallis. Fusce ultrices egestas orci, id pulvinar libero bibendum vel. Nunc malesuada, velit semper tincidunt faucibus, velit lorem vestibulum nisl, eu imperdiet neque massa nec libero. Aliquam porta posuere nibh, ut cursus tellus accumsan ac. Aenean efficitur aliquet est, a feugiat libero auctor quis. Etiam non varius diam.",
activeApplicants: 4,
dateOfPosting: "19/02/2022",
skillsets: ["HTML", "CSS", "Javascript", "Python", "C#", "React.js"],
salary: 40000,
},
{
    title: "Backend Developer",
    maxApplicants: 10,
    company: "TikTok",
    jobtype: "on-site",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sapien nibh, fermentum ut molestie ac, fringilla vitae augue. Aliquam tincidunt rhoncus molestie. Vestibulum ut vestibulum felis. Proin elementum velit vitae dolor mollis, a cursus odio interdum. Aenean posuere quam id lacus facilisis, et ultricies nulla feugiat. Morbi congue tincidunt eros in mollis. Donec mollis quis tortor eget tincidunt. Nunc elementum, risus pellentesque auctor rutrum, massa leo luctus felis, et feugiat eros tellus ut tellus. Etiam lacinia condimentum velit feugiat convallis. Fusce ultrices egestas orci, id pulvinar libero bibendum vel. Nunc malesuada, velit semper tincidunt faucibus, velit lorem vestibulum nisl, eu imperdiet neque massa nec libero. Aliquam porta posuere nibh, ut cursus tellus accumsan ac. Aenean efficitur aliquet est, a feugiat libero auctor quis. Etiam non varius diam.",
    activeApplicants: "",
    dateOfPosting: "",
    skillsets: ["Redux.js", "Node.js", "AWS", "MongoDB", "Socket.io", "Express.js"],
    salary: 40000,
    },
{
    title: "UI/ UX Designer",
    maxApplicants: 50,
    company: "Google",
    jobtype: "remote",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sapien nibh, fermentum ut molestie ac, fringilla vitae augue. Aliquam tincidunt rhoncus molestie. Vestibulum ut vestibulum felis. Proin elementum velit vitae dolor mollis, a cursus odio interdum. Aenean posuere quam id lacus facilisis, et ultricies nulla feugiat. Morbi congue tincidunt eros in mollis. Donec mollis quis tortor eget tincidunt. Nunc elementum, risus pellentesque auctor rutrum, massa leo luctus felis, et feugiat eros tellus ut tellus. Etiam lacinia condimentum velit feugiat convallis. Fusce ultrices egestas orci, id pulvinar libero bibendum vel. Nunc malesuada, velit semper tincidunt faucibus, velit lorem vestibulum nisl, eu imperdiet neque massa nec libero. Aliquam porta posuere nibh, ut cursus tellus accumsan ac. Aenean efficitur aliquet est, a feugiat libero auctor quis. Etiam non varius diam.",
    activeApplicants: "",
    dateOfPosting: "",
    skillsets: ["Figma", "Webflow", "HTML", "CSS", "Adobe Studio"],
    salary: 40000,
    },
{
    title: "Web3 Developer",
    maxApplicants: 90,
    company: "KFC",
    jobtype: "hybrid",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sapien nibh, fermentum ut molestie ac, fringilla vitae augue. Aliquam tincidunt rhoncus molestie. Vestibulum ut vestibulum felis. Proin elementum velit vitae dolor mollis, a cursus odio interdum. Aenean posuere quam id lacus facilisis, et ultricies nulla feugiat. Morbi congue tincidunt eros in mollis. Donec mollis quis tortor eget tincidunt. Nunc elementum, risus pellentesque auctor rutrum, massa leo luctus felis, et feugiat eros tellus ut tellus. Etiam lacinia condimentum velit feugiat convallis. Fusce ultrices egestas orci, id pulvinar libero bibendum vel. Nunc malesuada, velit semper tincidunt faucibus, velit lorem vestibulum nisl, eu imperdiet neque massa nec libero. Aliquam porta posuere nibh, ut cursus tellus accumsan ac. Aenean efficitur aliquet est, a feugiat libero auctor quis. Etiam non varius diam.",
    activeApplicants: "",
    dateOfPosting: "",
    skillsets: ["Etheruem", "Solidity", "Rust", "AWS", "Node.js", "Express.js"],
    salary: 50000,
    },
{
    title: "Devops",
    maxApplicants: 100,
    company: "Klarna",
    jobtype: "remote",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sapien nibh, fermentum ut molestie ac, fringilla vitae augue. Aliquam tincidunt rhoncus molestie. Vestibulum ut vestibulum felis. Proin elementum velit vitae dolor mollis, a cursus odio interdum. Aenean posuere quam id lacus facilisis, et ultricies nulla feugiat. Morbi congue tincidunt eros in mollis. Donec mollis quis tortor eget tincidunt. Nunc elementum, risus pellentesque auctor rutrum, massa leo luctus felis, et feugiat eros tellus ut tellus. Etiam lacinia condimentum velit feugiat convallis. Fusce ultrices egestas orci, id pulvinar libero bibendum vel. Nunc malesuada, velit semper tincidunt faucibus, velit lorem vestibulum nisl, eu imperdiet neque massa nec libero. Aliquam porta posuere nibh, ut cursus tellus accumsan ac. Aenean efficitur aliquet est, a feugiat libero auctor quis. Etiam non varius diam.",
    activeApplicants: "",
    dateOfPosting: "",
    skillsets: ["NoSQL", "MySL", "Express.js", "Typescript", "Javascript", "Kubernetes"],
    salary: 90000,
    },
{
    title: "Fullstack Developer",
    maxApplicants: 10,
    company: "Instagram",
    jobtype: "on-site",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sapien nibh, fermentum ut molestie ac, fringilla vitae augue. Aliquam tincidunt rhoncus molestie. Vestibulum ut vestibulum felis. Proin elementum velit vitae dolor mollis, a cursus odio interdum. Aenean posuere quam id lacus facilisis, et ultricies nulla feugiat. Morbi congue tincidunt eros in mollis. Donec mollis quis tortor eget tincidunt. Nunc elementum, risus pellentesque auctor rutrum, massa leo luctus felis, et feugiat eros tellus ut tellus. Etiam lacinia condimentum velit feugiat convallis. Fusce ultrices egestas orci, id pulvinar libero bibendum vel. Nunc malesuada, velit semper tincidunt faucibus, velit lorem vestibulum nisl, eu imperdiet neque massa nec libero. Aliquam porta posuere nibh, ut cursus tellus accumsan ac. Aenean efficitur aliquet est, a feugiat libero auctor quis. Etiam non varius diam.",
    activeApplicants: "",
    dateOfPosting: "",
    skillsets: ["Node.js", "Express.js", "Redis", "HTML", "AWS"],
    salary: 120000,
    },
{
    title: "Blockchain Developer",
    maxApplicants: 150,
    company: "Goil",
    jobtype: "hybrid",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sapien nibh, fermentum ut molestie ac, fringilla vitae augue. Aliquam tincidunt rhoncus molestie. Vestibulum ut vestibulum felis. Proin elementum velit vitae dolor mollis, a cursus odio interdum. Aenean posuere quam id lacus facilisis, et ultricies nulla feugiat. Morbi congue tincidunt eros in mollis. Donec mollis quis tortor eget tincidunt. Nunc elementum, risus pellentesque auctor rutrum, massa leo luctus felis, et feugiat eros tellus ut tellus. Etiam lacinia condimentum velit feugiat convallis. Fusce ultrices egestas orci, id pulvinar libero bibendum vel. Nunc malesuada, velit semper tincidunt faucibus, velit lorem vestibulum nisl, eu imperdiet neque massa nec libero. Aliquam porta posuere nibh, ut cursus tellus accumsan ac. Aenean efficitur aliquet est, a feugiat libero auctor quis. Etiam non varius diam.",
    activeApplicants: "",
    dateOfPosting: "",
    skillsets: ["Ethereum", "Solidity", "React.js", "Rust", "Javascript", "UI"],
    salary: 60000,
},
    {
    title: "PHP Developer",
    maxApplicants: 100,
    jobtype: "remote",
    company: "Meta",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sapien nibh, fermentum ut molestie ac, fringilla vitae augue. Aliquam tincidunt rhoncus molestie. Vestibulum ut vestibulum felis. Proin elementum velit vitae dolor mollis, a cursus odio interdum. Aenean posuere quam id lacus facilisis, et ultricies nulla feugiat. Morbi congue tincidunt eros in mollis. Donec mollis quis tortor eget tincidunt. Nunc elementum, risus pellentesque auctor rutrum, massa leo luctus felis, et feugiat eros tellus ut tellus. Etiam lacinia condimentum velit feugiat convallis. Fusce ultrices egestas orci, id pulvinar libero bibendum vel. Nunc malesuada, velit semper tincidunt faucibus, velit lorem vestibulum nisl, eu imperdiet neque massa nec libero. Aliquam porta posuere nibh, ut cursus tellus accumsan ac. Aenean efficitur aliquet est, a feugiat libero auctor quis. Etiam non varius diam.",
    activeApplicants: "",
    dateOfPosting: "",
    skillsets: ["Laravel", "Python", "Node.js", "AWS", "Socket.io", "PHP"],
    salary: 220000,
},
    {
    title: "Junior Frontend Developer",
    maxApplicants: 120,
    jobtype: "remote",
    company: "Youtube",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sapien nibh, fermentum ut molestie ac, fringilla vitae augue. Aliquam tincidunt rhoncus molestie. Vestibulum ut vestibulum felis. Proin elementum velit vitae dolor mollis, a cursus odio interdum. Aenean posuere quam id lacus facilisis, et ultricies nulla feugiat. Morbi congue tincidunt eros in mollis. Donec mollis quis tortor eget tincidunt. Nunc elementum, risus pellentesque auctor rutrum, massa leo luctus felis, et feugiat eros tellus ut tellus. Etiam lacinia condimentum velit feugiat convallis. Fusce ultrices egestas orci, id pulvinar libero bibendum vel. Nunc malesuada, velit semper tincidunt faucibus, velit lorem vestibulum nisl, eu imperdiet neque massa nec libero. Aliquam porta posuere nibh, ut cursus tellus accumsan ac. Aenean efficitur aliquet est, a feugiat libero auctor quis. Etiam non varius diam.",
    activeApplicants: "",
    dateOfPosting: "",
    skillsets: ["HTML", "CSS", "Javascript", "React.js", "Node.js", "Tailwind.css"],
    salary: 40000,
},
    {
    title: "Mid-level Frontend Developer",
    maxApplicants: 100,
    company: "RGT",
    jobtype: "remote",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sapien nibh, fermentum ut molestie ac, fringilla vitae augue. Aliquam tincidunt rhoncus molestie. Vestibulum ut vestibulum felis. Proin elementum velit vitae dolor mollis, a cursus odio interdum. Aenean posuere quam id lacus facilisis, et ultricies nulla feugiat. Morbi congue tincidunt eros in mollis. Donec mollis quis tortor eget tincidunt. Nunc elementum, risus pellentesque auctor rutrum, massa leo luctus felis, et feugiat eros tellus ut tellus. Etiam lacinia condimentum velit feugiat convallis. Fusce ultrices egestas orci, id pulvinar libero bibendum vel. Nunc malesuada, velit semper tincidunt faucibus, velit lorem vestibulum nisl, eu imperdiet neque massa nec libero. Aliquam porta posuere nibh, ut cursus tellus accumsan ac. Aenean efficitur aliquet est, a feugiat libero auctor quis. Etiam non varius diam.",
    activeApplicants: 17,
    dateOfPosting: "01/03/2023",
    skillsets: ["Redux", "Css", "React.js", "Typescript", "Javascript", "Bootstrap"],
    salary: 40000,
},
];

export default jobs;